### ISSUE TITLE
freeでの取りこぼしユーザーデータの取り直し

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#10]
app名：medicaljob.jp
bot_id：959

このappは、お金を払っていたにも関わらず、こちらのミスでなぜか無料プランに切り替わっており、メールが届いて発覚しました。その後、すぐに有料プランに変更して対応しましたが、このいちユーザーについては、anybotでのちほど追加することは可能でしょうか？

＊このクライアントは、selfonboarderなのに、２か月連続で二重課金されており、今回の件もあって不信感を抱かれているので、できれば追加してあげたいです。よろしくお願いします。

![unnamed](https://user-images.githubusercontent.com/48752463/66095076-2c8eea80-e5d1-11e9-8b09-466e437dde86.png)

**Comment by soyoes** [comment]
これはもう仕方がないです。申し訳ないです :( 。ただ、被害はここの一人だけです。
