### ISSUE TITLE
進学トーク : 学校の検索結果をrandom順で表示したい(mysqlのrandom)

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#104]

**Comment by northW** [comment]
![image](https://user-images.githubusercontent.com/4724297/67674226-ea31b100-f9b6-11e9-864f-b2040fd4f8fd.png)
現在の仕様は、ソート順はbot中にタグ検索と学校一覧はAPIのパラメーターで設定されました、キャプチャーと通り、第一ソート順はstat（A:Saas+進学，B:進学，C:未掲載）、二番目のソート順はsort（毎日で更新されるrandomソート順）

random順しかない場合は、apiのパラメーターで直接に`order=sort%20desc`で設定してください。
