### ISSUE TITLE
miniapp：営業時間の予約メッセージが表示されて会話が進まない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#108]
bot名：ラカラジャパン
bot_id：1164

Miniapp：「会社形態・利用する決済方法・紹介者・ご希望事項」
全て記入し「次へ」を押すと
「予約時間は営業時間ではありません」
OKを押して次へを押すと同じメッセージが表示され会話が進まない

![IMG_3317](https://user-images.githubusercontent.com/49668745/67544192-729e2080-f72f-11e9-9c01-f75a6021a7ca.PNG)

**Comment by cntomxu** [comment]
フォームタイプ：
予約フォーム => フォーム
デプロイ後、情報は表示されません。
