### ISSUE TITLE
ユーザ検索条件の追加

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#110]
ユーザ検索がIDか名前でしか検索できないので、電話番号や他のユーザ情報キーを元に検索できるようにしたい。

**Comment by soyoes** [comment]
一旦優先度が低い
名前がわかればそんなに問題にならない

**Comment by soyoes** [comment]
やる時はkey1=v1&key2@ne=v2 ...liberの標準queryで検索させればOK

**Comment by ToshikazuHorioka** [comment]
マージ時にインポートしていた名前よりLINEユーザ名が優先されるので、本名での検索ができなかった。
従業員番号などで検索もできなかった。
作業内容によっては名前だけではなく、色々なもので検索できるとありがたい。
by Five
