### ISSUE TITLE
chatflow:ユーザーの電波状況が原因でトーク画面に表示される回答内容がズレてしまう

### ISSUE THREAD

**Issue by ShinyaHirata** [Evolany/anybot_issues#117]
bot名：スタスタ
bot_id="531"

「利用規約に同意」の直前は「電話番号＝数字のみ」の設定ですので
そちらの内容リクエストとレスポンスが前後しているかと思われます。

![image](https://user-images.githubusercontent.com/55083366/67656952-9b751e80-f998-11e9-8298-0a082b7c2d3f.png)

![image](https://user-images.githubusercontent.com/55083366/67656985-c0699180-f998-11e9-9271-b5f9baed58aa.png)

**Comment by soyoes** [comment]
APIのレスポンス後のactionを使うことによって回避
