### ISSUE TITLE
LIFFで登録したユーザを削除後、再度友達になる時にthumbがencodeされている

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#118]
* LIFFで友達追加
* ユーザを管理画面で削除
* 問題1 : ユーザが再度LIFF友達追加で時に、blockedの状態になる
* 問題2 : ユーザが一回block、またunblockしたら、usernameは取れますが、thumbがurl encodeされている状態
https%3A%2F%2Fprofile.line-scdn.net%2F0hLFkRgyvkE2lWKz6WnSpsPmpuHQQhBRUhLktZWCAsSAkrGwBoPx5UCiEsS1ouTwQ7PRgPX3YtSF59

**Comment by cntomxu** [comment]
> 問題1
修正

問題2: 未再现
本地和本番上 尝试 block 或 unblock 后 再通过   miniapp访问 或者 直接访问 ，name和thumb都能正常保存。
我检索本番的db, 目前只有 bid=1243 里你的那个帐号是那样(uid=884)。
