### ISSUE TITLE
大学 : widgetのquick replyの表示は改行させたい

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#119]
![73041106_413261422900354_5973598827771330560_n](https://user-images.githubusercontent.com/1071779/67667359-fca8ec00-f9b0-11e9-964f-67e02c54b8c3.png)

**Comment by wheatup** [comment]
fixed on commit https://github.com/Evolany/anybot/commit/ef0a3e9280acc8fa697200bff09b1e7348643426
