### ISSUE TITLE
管理者の新規登録が出来ない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#12]
したい事
クライアントにリクエストされたユーザーを管理者に新しく登録したい

現在の状況
管理画面から新規管理ユーザーの登録ができない

こちらご確認お願い致します・

<img width="1290" alt="スクリーンショット 2019-10-03 14 39 15" src="https://user-images.githubusercontent.com/49668745/66102585-c9f81780-e5ed-11e9-9e51-148034f01cfe.png">

**Comment by soyoes** [comment]
App一覧 > 管理者より先に登録してください
