### ISSUE TITLE
miniapp : grids/list+contents API、かつ遷移先=URLの場合はapiから取得されたURLはurlencodingされている

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#121]
<img width="890" alt="Screen Shot 2019-10-29 at 11 17 45" src="https://user-images.githubusercontent.com/1071779/67732203-e7c66a00-fa3d-11e9-8eeb-d2441d245d5c.png">

bot : RB_DEMO

**Comment by cntomxu** [comment]
修正list/grid 的uri + view的迁移的uri

miniapp的url不会自己跳转，会打开LINE的web页，显示打开LINE APP的按钮的那个，

所以做了一下处理：
1. 处理url是miniapp的url时判断
  1.1 是当前bot的url,补齐q参数，并在当前的窗口打开。
  1.2 不是当前bot的url，转换成"line://"的url,重新打开新的liff窗口。
2. 不是miniapp的url不做特殊处理。
