### ISSUE TITLE
「イベント予約」と「次の会話」を両立する方法

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#131]
イベント予約をする際、「手動で指定」で「イベント予約」を設定する必要がありますが、それを設定すると次の会話が流れません。

現状は「次の会話を指定」で設定するしか方法がないので、Push通知の料金がかかってきてしまいます。

「イベント予約」と「次の会話」を両立する方法はありませんか？

**Comment by cntomxu** [comment]
「次の会話を指定」機能が復元されました
![image](https://user-images.githubusercontent.com/503743/68035104-ed51d780-fcfd-11e9-85d7-3a36c88cea70.png)

**Comment by ChikaKageyama** [comment]
ありがとうございます！
