### ISSUE TITLE
Quick Replyが表示されない

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#134]
![IMG_8203](https://user-images.githubusercontent.com/48752463/67917563-b1732100-fbdc-11e9-8015-72a9febbf632.PNG)

app名： factelier_demo

「イベントサンプル」のグループの「フォローアップ」にて、オフィスWiFiとキャリアの通信環境で試しましたが、Quick Replyの選択肢が表示されませんでした。

「再試行」というボタンを何回も触っていると、見えないけれど、どこかのボタンを押したように反応が出ました。

これはなぜQuick Replyが表示されないのでしょうか？

**Comment by liumu** [comment]
手動で再度イメージを作成して表示になりました。
