### ISSUE TITLE
設定した会話が表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#139]
anybot for college
BOT：帝京平成大学DEMO　bot ID=717
会話グループ：イベント情報
会話：7.名前_苗字→8.First_Name
の流れで
●8の「質問」が表示されません。
※テストではちゃんと表示されますが、LINEでは表示されません。
ただ応答はしているみたいで、名前を入力すれば、9の設問に遷移します。

![スクリーンショット 2019-11-01 16 55 57](https://user-images.githubusercontent.com/49668745/68010835-feccbc80-fcc8-11e9-96bb-520baeae7127.png)

![IMG_3392](https://user-images.githubusercontent.com/49668745/68010735-c7f6a680-fcc8-11e9-9f52-bf89fff167d8.PNG)

**Comment by cntomxu** [comment]
問題を修正しましたけど、botの設定について間違い所がありそう。
⑧First_Nameの「名前（名）を入力」ボタンの返信メッセージは、texthandle（選択式ボタンを追加）に移動して方がいいです。
「名前（名）を入力」ボタンは LINE入力モード切替 なので、Lineでボタンをクリックすると、返信メッセージはLineの入力Boxに反映されます。

![image](https://user-images.githubusercontent.com/503743/68035922-a06f0080-fcff-11e9-874b-4cde88a7654b.png)

**Comment by cntomxu** [comment]
![image](https://user-images.githubusercontent.com/503743/68035962-afee4980-fcff-11e9-9df5-c4c1a1b74767.png)
