### ISSUE TITLE
Miniapp：会話に遷移しない・メールが送信されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#14]

**Comment by ayakishimizu** [comment]
bot名：イシカワ問合せ　
bot_id：974

ミニアプリ[選択用データ一覧]→[お届け先]→メール送信、会話[完了お礼]遷移を指定

![スクリーンショット 2019-10-04 16 19 04](https://user-images.githubusercontent.com/49668745/66188795-2a0cbd80-e6c3-11e9-8672-29bd93145a8c.png)

10/03 22:09の送信を最後に、拡張機能で設定したメールが送信されず、
ミニアプリは閉じず指定した会話にも遷移出来なくなったそうです。

**Comment by soyoes** [comment]
@cntomxu 修正されていない
