### ISSUE TITLE
miniapp：注文済み一覧の{{desc}}が表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#143]
bot名:イシカワ EC
bot_id：767

miniapp：注文済み一覧→miniapp：注文アイテム詳細
詳細の設定
<img width="605" alt="スクリーンショット 2019-11-05 19 26 08" src="https://user-images.githubusercontent.com/49668745/68200111-90f2fe80-0002-11ea-85e1-81bbd4563a11.png">
問題：
{{title}}と{{price}}は反映されているが

{{desc}}のみLINEに反映されない。
![IMG_3466](https://user-images.githubusercontent.com/49668745/68200228-c861ab00-0002-11ea-8ba7-264bab0ae1f2.PNG)

**Comment by cntomxu** [comment]
修正しました、本番は更新しました。

{{desc}}は商品詳細のdescを取得できます。

実際、これは注文です。注文にはdescフィールドはありません。
注文のdescに商品詳細のdescを手動で渡しました。

さらに、他の商品の情報も注文に追加されます。
このようにすることもできます
```
{{item.title}}
{{item.desc}}
{{item.desc}}
```
今のところ必要ありません。。
