### ISSUE TITLE
:LINE webhookに接続ができない

### ISSUE THREAD

**Issue by ShinyaHirata** [Evolany/anybot_issues#146]
bot名：ひよ子
bot id:1336
LINEの接続状況は確認済みで問題ないが、webhook接続ができない状況です。
確認のほどよろしくお願いします。

**Comment by liumu** [comment]
Lineのアクセス制限を設定されたそうです。
以下のIPアドレスをホワイトリストに追加し、再度お試してください。

```
13.114.176.92
52.199.191.194
18.179.23.217
18.182.62.147
13.115.142.252
54.248.204.20
```
