### ISSUE TITLE
{{user.product_grids}}で商品が一つしか表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#147]
bot名：イシカワEC
bot_id：767

ミニアプリ:ONLINE SHOPで商品を複数選択>お届け先選択>注文確認

{{user.product_grids}}で商品情報が一つしか表示されないようです。

<img width="350" alt="スクリーンショット 2019-11-06 20 00 44" src="https://user-images.githubusercontent.com/49668745/68292897-2dcf9d80-00d0-11ea-9f06-6212866e2de0.png">

**Comment by cntomxu** [comment]
![image](https://user-images.githubusercontent.com/503743/68371563-f3bad600-0179-11ea-86de-0060ab8870f4.png)
