### ISSUE TITLE
Bot-export/import時に、segmentation情報とminiappもexport/import対象にする

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#151]

**Comment by ToshikazuHorioka** [comment]
テンプレートのBOTID：1329

BOTID :  1366

1. 会話フローからミニアプリへの遷移設定が反映されていません。
2. 店舗が登録されていない

よろしくお願い致します。

![Screenshot 2019-11-12 at 15 39 49](https://user-images.githubusercontent.com/47316607/68648283-5853a780-0563-11ea-931e-b44429098a2a.png)

**Comment by ToshikazuHorioka** [comment]
テンプレートのBOTID：1329
BOTID : 1375

テンプレートから新規作成したBOTです。
LINEに繋いだ後、リッチメニューを押しても設定通りの会話が実行されませんでした。

![Screenshot 2019-11-14 at 21 32 33](https://user-images.githubusercontent.com/47316607/68857525-4e2dd680-0726-11ea-9026-b23c1d5f1f64.png)

![IMG_A7AD77D3B1C5-1](https://user-images.githubusercontent.com/47316607/68857596-70bfef80-0726-11ea-8b2a-88cddd5dd2f4.jpeg)


ごかくご確認よろしくお願い致します。

**Comment by cntomxu** [comment]
@ToshikazuHorioka 

それを確認した、インポートとは関係ありません

LINEはanybotのwebhookインターフェイスを呼び出しませんでした。webhookの設定が正しいことを確認してください。
