### ISSUE TITLE
ユーザデータに新たなカウンターを追加、イベントやECなど

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#157]
- [ ] contact_c        = "int default 0 COMMENT 'inquiry cnt'"
- [ ] event_resv_c     = "int default 0 COMMENT 'events reserve cnt'"
- [ ] event_come_c     = "int default 0 COMMENT 'events attend cnt'"
- [ ] event_cancel_c   = "int default 0 COMMENT 'events cancel cnt'"
- [ ] rms_resv_c       = "int default 0 COMMENT 'store rms reserve cnt'"
- [ ] rms_come_c       = "int default 0 COMMENT 'store rms attend cnt'"
- [ ] rms_cancel_c     = "int default 0 COMMENT 'store rms cancel cnt'"
- [ ] ec_buy_c         = "int default 0 COMMENT 'ec bought times cnt'"
- [ ] ec_buy_items_c   = "int default 0 COMMENT 'ec bought items cnt'"
- [ ] ec_buy_total     = "int default 0 COMMENT 'ec bought subtotal'"
- [ ] ec_return_c      = "int default 0 COMMENT 'ec return items cnt'"
- [ ] coupon_receive_c = "int default 0 COMMENT 'coupon receive cnt'"
- [ ] coupon_use_c     = "int default 0 COMMENT 'coupon use cnt'"

**Comment by cntomxu** [comment]
coupon_receive_c
coupon_use_c
