### ISSUE TITLE
アプリの編集者の追加

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#166]
アプリの編集者の追加について確認お願いします。
現在は、以下の流れです。

アプリの「編集者」＞「編集者招待」＞「担当者」を選択＞「保存」

上記の流れで、エボラニスタッフは、anybotに登録している全てのユーザーを追加できるようですが、同姓同名の人が登録あったりして間違いがおきそうなので、「保存」の後に、「名前」と「会社名」を確認できる画面を追加していただくことは可能ですか？

**Comment by soyoes** [comment]
お客さんの場合は自社のスタッフしか見れないので、大丈夫じゃないのかな

**Comment by ChikaKageyama** [comment]
どちらかというとエボラニ社内のミスを防ぐためです。
anybotのユーザーも、社員も増えてきている
例：
Shinya Hirata
Shinya Hirada

わかりにくかったので調べたところShinya Hiradaは平田さんだったのでこちらで名前を修正しました。

上記のような例があった場合や、ローマ字で同姓同名の場合、会社名がないとどこの誰を追加しているかわからない

**Comment by liumu** [comment]
![image](https://user-images.githubusercontent.com/5706609/68676366-daa88f80-0594-11ea-8c15-c6ed9226abab.png)

![image](https://user-images.githubusercontent.com/5706609/68676396-e98f4200-0594-11ea-8da0-4113f60eea63.png)

上記のように変更した。
