### ISSUE TITLE
友だち招待機能がうまく作動しません。

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#172]
app名：サンスターdemo
会話グループ：　友だち招待
①の「お友だちを招待する」から、友だちを招待して、相手がリンクを踏んでも、設定した会話が招待した側に発動しません。

先ほどまでは動いていて、少し変更したのですが、戻したところ、まったく動かなくなってしまいました。

確認お願いします。

**Comment by cntomxu** [comment]
テストして、アクションを受け取ることができました。
さらに、ユーザーが正常に招待された場合、
招待を繰り返さず、アクションを再度送信しません

**Comment by cntomxu** [comment]
{{name}}  => {{user.name}} または {{姓名}}

**Comment by cntomxu** [comment]
または、これから直接選択します
![image](https://user-images.githubusercontent.com/503743/68739550-12aae380-0624-11ea-8474-839c4a29fd7e.png)

**Comment by soyoes** [comment]
@cntomxu 我也试了不好用

**Comment by soyoes** [comment]
https://line.me/R/app/1653497745-aYyZxmA9?type=app&b=1347&v=721&refrid=85370&refcode=0V1VWL1QGAE8&ref=invite
