### ISSUE TITLE
自動セグメントの「Refパラメータ」と「タグ」の違い

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#173]
＞「Refパラメータ」は、会話作成の際に自動で作られたパラメータ一覧です。
＞「タグ」は、会話作成の際に自動で作られたパラメータ一覧と、手動で作成したタグ一覧です。

↓
・この2つの違いが分かりません。「Refパラメータ」にも手動で作成したタグが加わります。
・手動で作成したタグが削除できません。以前はできていました。ご確認ください。

添付画像の二つめ
[1113A質問.pdf](https://github.com/Evolany/anybot_issues/files/3839503/1113A.pdf)

確認お願いします。

**Comment by cntomxu** [comment]
Refパラメータ: urlのref_xxxパラメーターによって生成されたこのタグはシステムに属しているため、手動で削除しないでください。
ユーザーの編集画面のタグは、ユーザーに自由に追加できるタグであり、一部はイベント予約などの特別な場合に自動的に生成されます。
ユーザータグは削除できません 、修正しました。夜間に環境を更新します。

**Comment by cntomxu** [comment]
ユーザーリストからユーザータグを削除することもできます
![image](https://user-images.githubusercontent.com/503743/68738072-4be15480-0620-11ea-925d-6b52d2b0602c.png)

**Comment by cntomxu** [comment]
ユーザーリストからユーザータグを削除することもできます。

**Comment by ChikaKageyama** [comment]
自動セグメントの「Refパラメータ」と「タグ」は現状同じ内容が出るバグが発生している。
優先度低めですが、お時間ある際に修正お願いします。

<img width="168" alt="キャプチャ2" src="https://user-images.githubusercontent.com/48752463/68835531-a13e6400-06fb-11ea-9b3e-34bdb3141190.PNG">
<img width="167" alt="キャプチャ" src="https://user-images.githubusercontent.com/48752463/68835532-a1d6fa80-06fb-11ea-9468-2f102e89bf69.PNG">
