### ISSUE TITLE
友だち招待の機能の追加希望

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#175]
①
友だち招待機能で、友だち招待人数の自動セグメントはできますが、どの友だちがどの友だちを招待したか、の紐づけは可能ですか？

②
現在、友だちに送信する際のリンクが長いので、短いリンクを利用することは可能ですか？

③
友だちに送信する際に、記載するメッセージを設定する、ようなことは可能ですか？

④
現在、招待された友だちがリンクを踏んだ瞬間に招待した、とカウントされますが、招待された友だちが行ったアクション（例：アンケートを最後まで答えた）を元に、招待した人数としてカウントすることは可能ですか？

**Comment by soyoes** [comment]
全部できた

**Comment by ChikaKageyama** [comment]
以下はどこでできますか？

①
友だち招待機能で、友だち招待人数の自動セグメントはできますが、どの友だちがどの友だちを招待したか、の紐づけは可能ですか？

②
現在、友だちに送信する際のリンクが長いので、短いリンクを利用することは可能ですか？

④
現在、招待された友だちがリンクを踏んだ瞬間に招待した、とカウントされますが、招待された友だちが行ったアクション（例：アンケートを最後まで答えた）を元に、招待した人数としてカウントすることは可能ですか？


【以下、確認済】
③　友だちに送信する際に、記載するメッセージを設定する、ようなことは可能ですか？

@ayakishimizu FYI
