### ISSUE TITLE
ref-URLのQR発行機能を追加してください。

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#176]
ミニアプリなどのref-urlをQRコードにする機能を追加していただけますでしょうか。

利用例：
QRコードを印刷して、
読み取ったら、ミニアプリのアンケートが始まる。

**Comment by soyoes** [comment]
@cntomxu 
跟你之前做的店铺的那个qr功能一样的popup也加到miniapp的编辑画面吧。右上角。右边留16px的margin
