### ISSUE TITLE
app編集者追加後の通知メールを修正してください。

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#181]
現在、添付の通知メールが来ますが、足りない情報が多いので、修正してください。

<img width="286" alt="キャプチャ" src="https://user-images.githubusercontent.com/48752463/68822085-527cd400-06d3-11ea-8a86-a02d8698330f.PNG">

以下が変更イメージです。

TITLE: [anybot]アプリへの招待が届きました

Contents:
![Group 1](https://user-images.githubusercontent.com/48752463/68822093-57da1e80-06d3-11ea-9c38-53e3041f1ddc.png)
*赤い部分はパラメーターの利用希望です。

https://www.figma.com/file/AiAW3jVMJ7DYuiXV40inI0/anybot-UI-UX?node-id=0%3A1

**Comment by ChikaKageyama** [comment]
![Frame 1](https://user-images.githubusercontent.com/48752463/68822209-aab3d600-06d3-11ea-9aff-cbba011c12af.png)
Figma見れない時のために、依頼内容も送ります。

**Comment by soyoes** [comment]
@evolany-kotori 人数オーバーのメールテンプレートを参照してください。
変に太文字や、赤色を使わないようにｗ
