### ISSUE TITLE
college：バッジがないのにカウントされている

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#184]
anybot for college
bot名「神戸ベルェベル美容専門学校：bot ID=593」

バッジがついているユーザーがいないのに、
ユーザー　＞　「標準セグメント」　＞　「未解決一覧」に①が表示されています。
こちらは全て対応済であることを確認し、バッジがついているユーザーはいないので、
表示を修正してください。

<img width="234" alt="キャプチャ" src="https://user-images.githubusercontent.com/48752463/68835837-507b3b00-06fc-11ea-8386-82040ec45adb.PNG">

**Comment by liumu** [comment]
FIXした。
