### ISSUE TITLE
APP設定の「利用する機能」が反映されません。

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#185]
APP設定の「利用する機能」が反映されません。

以前、「EC」を設定したのにECが表示されず、宋さんに直してもらいましたが、
今回、app名：クラブツーリズムdemo　でも、「イベント」や「予約」がメニューに表示されません。

私のアカウントの権限の問題でしょうか？

確認お願いします。

![Group 41](https://user-images.githubusercontent.com/48752463/68855419-87177c80-0721-11ea-8e26-0dd1f70834e7.png)
![Group 42](https://user-images.githubusercontent.com/48752463/68855425-88e14000-0721-11ea-9475-0dbc16180562.png)

**Comment by liumu** [comment]
![image](https://user-images.githubusercontent.com/5706609/68861056-b9c37400-0725-11ea-9781-5e172b79dd1a.png)
チカさんのアカウントは上記スクショによって、このBOTに対するECなど権限が持っていません。
