### ISSUE TITLE
新規友人追加時に設定したメッセージが表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#191]
アピア(bot_id：1338)のデフォルトグループの会話についてです。
要望：
**新規友人追加後の会話フロー[デフォルトグループ]で⑥回答後に7もしくは8のメッセージを表示させたい。**
現状
新規で友だち追加した時のみ[デフォルトグループ]❼❽のメッセージが表示されないようです。
https://line.me/R/ti/p/@511otryz

ブロック→解除後では同じ会話をしてメッセージが表示されました。
![iOS の画像 (3)](https://user-images.githubusercontent.com/49668745/69019437-0348e300-09f4-11ea-80da-a91067379848.jpg)

**Comment by cntomxu** [comment]
これはバグではなく、プロセスの問題です。

「新規登録時の会話」を変更しました。

問題は解決されているはずです、
テスト後は問題ありません。
![image](https://user-images.githubusercontent.com/503743/69688427-ff5a4680-1100-11ea-84fd-1cceb116aefb.png)
