### ISSUE TITLE
一括配信ができない

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#193]
app名：anybot社内用、Evolany社内事務用

上記のアプリで試しましたが、一括配信ができません。
以下を試したいです。

・一括配信の時差　からの　「次のメッセージを指定」の時差
・「次のメッセージを指定」の「１日後」の検証
・一括配信の動画配信が可能かどうか

**Comment by cntomxu** [comment]
Broadcastサーバーの1つが停止し、再起動されました
