### ISSUE TITLE
過去に配信された会話が一括送信された

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#198]
AWAKE検証用(894)

[【AW】テスト配信]を対象にした[谷・江テスト配信一括配信]の①イメージ カルーセルを配信
配信処理のメッセージは届くが対象の一括配信は配信されず、
代わりに[テスト配信 1]→[①画像]が届いた

配信済み記事のサムネは対象のイメージカルーセルの画像が反映されています。
![スクリーンショット 2019-11-20 17 58 18](https://user-images.githubusercontent.com/49668745/69224183-70f53a80-0bbf-11ea-944e-ce746d303f03.png)

**Comment by cntomxu** [comment]
また、ボタンを追加する必要があります
