### ISSUE TITLE
セグメントに該当しないユーザーが表示される

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#199]
アピア(bot_id：1338)

下記の内容でセグメント[未入力]を作成
![スクリーンショット 2019-11-20 19 15 26](https://user-images.githubusercontent.com/49668745/69230528-c2ef8d80-0bca-11ea-8cde-ddc25526c839.png)

セグメントを確認すると会員番号を入力しているユーザーが含まれている。
例：[ID：167]まことっちゃん

会話履歴を確認すると会員番号{{members_card}}を入力はしているが
チャット会員番号に反映されていない
例：[ID：2511]

![スクリーンショット 2019-11-20 19 36 48](https://user-images.githubusercontent.com/49668745/69232475-773ee300-0bce-11ea-8405-b3763b5a23ee.png)

**Comment by cntomxu** [comment]
[ID：2511]
「会員番号」と答える前に、メニューをクリックしました。
プロセスが壊れ、保存データがなく、次の会話の実行がありません



[ID：167]
回答の時点では、ukeyは指定されておらず、members_cardは指定されていません
ちょうどデフォルト値c_6691_33838_ipts
