### ISSUE TITLE
Miniapp:選択用データ一覧で商品選択数が表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#2]
bot名：イシカワ問い合わせ バックアップ
bot_id：974

要望：
Product_listで選択・**指定した商品の数量**をUkeyで表示させたい
![Miniapp_catalog](https://user-images.githubusercontent.com/49668745/65848439-11c63700-e381-11e9-9fcb-11ee9c7e25a2.png)
![IMG_3030](https://user-images.githubusercontent.com/49668745/65848455-21458000-e381-11e9-9527-7b95473a5ace.PNG)

商品選択→お届け先[送信する]ボタンにmail通知設定
![スクリーンショット 2019-09-30 12 54 20](https://user-images.githubusercontent.com/49668745/65848553-8dc07f00-e381-11e9-94a7-4df57a4fc390.png)

メールで{{user.product_list}}で選択商品名は表示できたが
選択商品で指定された数字は取得出来ませんでした。

![IMG_3028](https://user-images.githubusercontent.com/49668745/65848582-ae88d480-e381-11e9-9f5d-bc10577d0bc7.PNG)

**Comment by soyoes** [comment]
@ayakishimizu 
これ対応済みですよね？？
