### ISSUE TITLE
基本設定を保存するとエラーメッセージがでる

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#200]
昨日から、基本設定を変更して保存すると、保存完了の後にエラーメッセージが表示されます。

![image](https://user-images.githubusercontent.com/48752463/69292310-1f918d80-0c49-11ea-8520-17b660bde815.png)

**Comment by cntomxu** [comment]
API アクセスキー  生成するために必要

**Comment by soyoes** [comment]
@ChikaKageyama @ToshikazuHorioka 現在の状況を教えて、終わったらクローズして

**Comment by ToshikazuHorioka** [comment]
対応済みです
