### ISSUE TITLE
予約日時によるリマインド設定、リマインドメッセージが送信されない

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#201]
BOTID ： 1379
会話：「来院予約」→「5.日時既存」と「6.日時新規」

予約した日時の1日前の8時に指定メッセージが送信されなかった

![Screenshot 2019-11-21 at 10 39 33](https://user-images.githubusercontent.com/47316607/69293095-3fc24c00-0c4b-11ea-8c21-ec112ce6ba87.png)

**Comment by cntomxu** [comment]
@ToshikazuHorioka 

dbのデータから、指定された時間のセッションデータは生成されません。

自分のアカウントを使用してテストします
再現されません。

9回の予定をテストしましたが、再現できませんでした。
スケジュールされたセッションを生成および受信しました。

私のテストデータが削除されました

再テストがある場合はお知らせください。dbがデータを生成するかどうかを確認できます。
