### ISSUE TITLE
dricomユーザーがリストの人数と違う

### ISSUE THREAD

**Issue by mkitamoto** [Evolany/anybot_issues#207]
・「最初訪問日」「最終訪問日」「年齢」について、ユーザ数がリストの人数と違います。  

BotID：６２５
Bot名：ロイヤル学園DEMO

<img width="1167" alt="キャプチャ1" src="https://user-images.githubusercontent.com/57471333/69304215-2d540c80-0c63-11ea-9a20-5f855164ba9c.PNG">

**Comment by soyoes** [comment]
次の更新時に反映させます
