### ISSUE TITLE
自動セグメントの名前をセグメンテーションと統一してください。

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#208]
自動セグメントの「最初訪問日」を「登録日」に変更してただけますか？

セグメンテーションと統一したいです。

![image](https://user-images.githubusercontent.com/48752463/69306460-d18d8180-0c6a-11ea-9e33-7d258f053243.png)

**Comment by soyoes** [comment]
@ChikaKageyama 
このようにタイトルを書いてください
anybot for college 「最初訪問日」を「登録日」に変更 #213

環境 > 機能/画面 > 何をする(詳細のキーワード)
