### ISSUE TITLE
request：コンテンツ一覧>[EC商品]から選択した場合はproduct_list変数に保存されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#21]
bot名：肉の丸小
bot_id：940

ミニアプリ：コンテンツ一覧>[EC商品]
商品と注文数を選択>catalog{{product_list}}のように
取得した情報をukeyで参照したい

**Comment by cntomxu** [comment]
変数が保存されました
ミニアプリには、list（オプションのデータ一覧）と grids（コンテンツ一覧）があります
list使用変数名は  {{user.product_list}} です。
grids使用変数名は  {{user.product_grids}} です
このボットはgridsに使用する必要があります。
したがって、 {{user.product_grids}} を使用する必要があります
