### ISSUE TITLE
一部のセグメントが指定できない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#210]
VIVO(bot_id：1243)

会員証>性別[男性]
会員証>性別修正用[男性]でセグメント[検証1121 会員証 男性]を作成

<img width="1204" alt="スクリーンショット 2019-11-21 14 44 31" src="https://user-images.githubusercontent.com/49668745/69308593-ef5ce580-0c6e-11ea-92bd-f9fc1c520226.png">

作成したセグメントを確認すると
**会員証>性別[男性]
会員証>性別修正用[男性]**が指定されておらず、
設定してない　プレオープン DONT EDIT>性別 [男性]が指定されていた。

<img width="982" alt="スクリーンショット 2019-11-21 14 45 23" src="https://user-images.githubusercontent.com/49668745/69308829-000d5b80-0c6f-11ea-93f0-954823ec2ce7.png">

**Comment by soyoes** [comment]
私も再現しました。

**Comment by soyoes** [comment]
自動セグメント　＞　性別別を使ってください
