### ISSUE TITLE
セグメントで表示されないユーザーデータがある

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#212]
VIVO(bot_id：1243)

REF_GENDER [男性]

プレオープン DONT EDIT>性別 [男性]でセグメント[男性]を作成
検索しても該当セグメントに表示されないユーザーがいる

例：
[ID：12]なんちゃん

REF_GENDER [男性]
プレオープン DONT EDIT>性別 [男性]
会員証 >性別[男性]
会員証>性別修正用[男性]
<img width="1133" alt="スクリーンショット 2019-11-21 14 51 15" src="https://user-images.githubusercontent.com/49668745/69311491-cbe66a80-0c6f-11ea-9e62-fa6732b9c946.png">

**Comment by soyoes** [comment]
重複
