### ISSUE TITLE
店舗タイトルが反映されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#214]
RB_demo(1142)

ミニアプリ：ACE詳細で表示された名前{{title}}をメールに反映したい。

![スクリーンショット 2019-11-21 17 46 24](https://user-images.githubusercontent.com/49668745/69321846-2a6b1300-0c87-11ea-951b-d14012f79da2.png)

メール記入内容
{{user.title}}

![スクリーンショット 2019-11-21 17 46 10](https://user-images.githubusercontent.com/49668745/69321993-6b632780-0c87-11ea-8f71-1d267b246e42.png)

メールでは{{user.title}}が反映されませんでした
![IMG_3652](https://user-images.githubusercontent.com/49668745/69322120-a1a0a700-0c87-11ea-8978-0dacd9d6237d.PNG)

**Comment by soyoes** [comment]
それはちょっと難しいですね。。。
今の変数は詳細画面に代入しているだけで、ユーザ情報として保存されてるのはstore_idだけですね。

**Comment by ToshikazuHorioka** [comment]
@ayakishimizu 
修正したので、確認お願いいたします。
