### ISSUE TITLE
CSVインポート成功メッセージ表示されるがデータが見つからない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#217]
アピア(bot_id:1338)

ユーザーCSVのサンプルを作成しインポートの成功メッセージは出たのですが、
インポートした名前：清水彩紀　で検索しても該当ユーザーデータが見つかりませんでした。

![スクリーンショット 2019-11-22 10 16 51](https://user-images.githubusercontent.com/49668745/69390404-7ca54600-0d12-11ea-836f-26aadd886d4d.png)
![スクリーンショット 2019-11-22 10 17 07](https://user-images.githubusercontent.com/49668745/69390408-80d16380-0d12-11ea-9424-f23c8da01e95.png)

**Comment by liumu** [comment]
既存データのid:55ユーザへマージしたので、sdkユーザに存在しません。
