### ISSUE TITLE
Miniapp：parameterが正常に作動しない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#22]
bot名：肉の丸小
bot_id：940

ミニアプリ：[弁当予約] EC商品 parameter **category=弁当**を指定
**issue**
指定していない **category=持ち帰り**が表示される

![IMG_3116](https://user-images.githubusercontent.com/49668745/66282438-5d855d00-e8fa-11e9-8bd9-53be923565a4.PNG)

**Comment by soyoes** [comment]
@ayakishimizu 
パラメータ : category=cate1,cate2
タブメニューの場合は tab=cate1
