### ISSUE TITLE
送信済みの一括配信が再度送信

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#24]
bot名：LOVOT
bot_id：869

10/04  12:30に配信したメッセージ[20191004配信]が13:19に送信
その後配信設定をしていない同一のメッセージが同日17:17に送信された
※配信履歴に情報無し

![iOS の画像 (2) (2)](https://user-images.githubusercontent.com/49668745/66283872-274adc00-e900-11e9-9ed0-e90d1b40952f.png)

**Comment by soyoes** [comment]
@liumu @northW @cntomxu 

```
select * from (
    select m.uid,group_concat(m.bcid) 'bids',group_concat(FROM_UNIXTIME(m.ins_t)) 'dates',a.name from msgs_869 m left join accounts_869 a on m.uid=a.id where m.aid = 30868 group by m.uid
) mm where bids like '%,%';

```

一共157个人发生了这种情况
原因不明
这个action(30868)作为next action登录的，收到的肯定是通过触发前一个action（30873) 的next过来的。

**Comment by soyoes** [comment]
https://github.com/Evolany/anybot_issues/issues/135
同根
