### ISSUE TITLE
Clinic : リッチメニュー上のTEL: URLの対応

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#26]

**Comment by ToshikazuHorioka** [comment]
LINE URLスキームで対応しているのはLINE OUT画面を開く＆デフォルト番号の設定のみ。
実際に電話を繋げることはできない。

LINE OUTのUIに抵抗があれば、テキストで電話番号を吐き出し、ユーザに電話番号をタップしてもらって電話させる方法もあり。

**Comment by ToshikazuHorioka** [comment]
リッチメニューだけではなく、会話フロー内でもtel://のURL直接アクセスで通常の電話ができるようにする。
