### ISSUE TITLE
bot:定期配信機能を利用してステップ配信ができるようにしたい

### ISSUE THREAD

**Issue by ShinyaHirata** [Evolany/anybot_issues#263]
bot名：anybot.me
bot_id="741"

1日目の登録者にAのスタティックコンテンツを朝7-9時に配信
2日目の登録者にBのスタティックコンテンツを朝7-9時に配信
3日目の登録者にCのスタティックコンテンツを朝7-9時に配信
という形で設定しましたがメッセージが届きませんでした。

学校・塾や各種教室、その他スポーツジムやエステ・保育園自動車学校など
入会・入校してから継続的にコミュニケーションが発生する分野の
お客様から、こちらが実現できればすぐに導入したいという声が
かなり上がっており汎用性が高い機能で、販売代理店からも、
同じ要望が沢山きている内容ですので、設定方法が間違っているかも含めて
なるべく早く調べて頂けますと幸いです！

現在の設定　
1日目の登録者
![image](https://user-images.githubusercontent.com/55083366/70047961-7c5b5380-160c-11ea-839d-55b89776eda2.png)

![image](https://user-images.githubusercontent.com/55083366/70047995-96953180-160c-11ea-83cd-c4929ce8f2fe.png)

**Comment by northW** [comment]
登録日X日前からY日前の間　の意味は
登録の時間はシステム現在時間よりX日前からY日前の間
つまり、1日前から0日前の間の意味は
例えば今10時の場合：昨日10時から今まで（現在10時）登録のユーザ
![image](https://user-images.githubusercontent.com/4724297/70291189-610f6480-1815-11ea-8c3b-37130767022a.png)

**Comment by soyoes** [comment]
@northW 不是让你回答式样问题而是看看这个需求怎么解决
比如用户登录第一天的时候用定期发信的功能发第一个消息，
第2天发第2个消息。。。
现在只能依靠action或reaction的next设定，这里有很多问题。比如指定的是第2天不假，但是发过来的时间是第一天的时刻+24h，可能会半夜发消息过来
