### ISSUE TITLE
ミニアプリがTOPメニューに表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#281]
Dricom(bot_id：255)https://college.anybot.me/

【ミニアプリ】キャンペーン_アンケートをTOPメニューに表示させる設定後、
メニュー右にキャンペーン_アンケートの名前は表示されるが、
項目が表示されませんでした。
![スクリーンショット 2019-12-10 11 52 34](https://user-images.githubusercontent.com/49668745/70491414-9208d580-1b44-11ea-89de-30e9418e4046.png)

![スクリーンショット 2019-12-10 12 02 02](https://user-images.githubusercontent.com/49668745/70491560-e8761400-1b44-11ea-93c1-d5454a913279.png)

**Comment by liumu** [comment]
![image](https://user-images.githubusercontent.com/5706609/71503959-5d21b000-28b2-11ea-9b61-3e92334b07a1.png)
別の修正ですでに直したそうです、再現なし
