### ISSUE TITLE
LINEで新規登録する際にmemberテーブルのcompany_id=NULL

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#294]
おそらくこれがうまく実行されていないのは原因
show_basic_info_form()

**Comment by evolany-kotori** [comment]
1)
lineで新規登録された時に、company_id=NULLの場合
企業情報入力で離脱した人たち

lineでログインした後に、line_id, tokenなど一度membersテーブルに保存される。
その後、企業情報を入力すると一度membersテーブルに保存されたものが正しくアップデートされる。
membersのtype=11

2)
lineで新規登録かつ、個人で利用の場合　
company_id, company_nane はNULL
membersのtype=1
