### ISSUE TITLE
リッチメニュー：マイ予約一覧　カルーセルのボタンカスタマイズ＋予約キャンセルON/OFF

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#311]
- [ ] 1/10までにお願いいたします

リッチメニューから「店舗予約一覧」を表示させる機能について運用上の問題があるため機能強化をお願いしたいです。

予約キャンセルは、一部のクライアントはLINEユーザがキャンセルする前に1度確認を挟む必要があります。なので、カルーセル下のボタンを指定の会話へリンクさせるなど自由に設定できるようにしたいです。

1. カルーセル→コンテンツのプルダウンに「マイ予約」を追加したいです
2. カルーセル下の任意のボタンが押された際に「rms_cancel_id」をユーザに保存させたい
3. 拡張機能->RESERVATIONのフォームで予約キャンセルのON/OFFができるようにして欲しいです。

![Screenshot 2019-12-25 at 18 18 13](https://user-images.githubusercontent.com/47316607/71442264-86263180-2748-11ea-8858-d029f19ce947.png)
![Screenshot 2019-12-25 at 18 18 46](https://user-images.githubusercontent.com/47316607/71442265-86bec800-2748-11ea-9eeb-37ff754d3b00.png)

**Comment by ToshikazuHorioka** [comment]
下記BOTで検証しましたが、上手くいきません。
設定方法が間違っていますか？
確認お願いいたします。
BOT ID : 1329

![IMG_019E18534B05-1](https://user-images.githubusercontent.com/47316607/72153362-22ab2d80-33f1-11ea-90dc-0cca3d442049.jpeg)

![Screenshot 2020-01-10 at 21 33 37](https://user-images.githubusercontent.com/47316607/72153372-2b036880-33f1-11ea-8e96-8d4c14c8c1ae.png)

**Comment by ToshikazuHorioka** [comment]
バグを発見いたしました。

BOT ID : 1329

会話作成
![Screenshot 2020-01-10 at 21 33 37](https://user-images.githubusercontent.com/47316607/72153505-8a617880-33f1-11ea-8950-3496e8ea70b9.png)

ページリフレッシュすると会話の設定が初期化される
![Screenshot 2020-01-10 at 21 36 54](https://user-images.githubusercontent.com/47316607/72153543-a533ed00-33f1-11ea-8c29-15578742cd4a.png)

もう一度、コンテンツ→予約店舗一覧を選択＆新規ボタン追加すると、以前追加したボタンが現れる
![Screenshot 2020-01-10 at 21 37 45](https://user-images.githubusercontent.com/47316607/72153602-c98fc980-33f1-11ea-81ca-efa1ae81baac.png)

**Comment by cntomxu** [comment]
本番は修正しました。
myrmsが空のデータを返すと、LINE側にxxxメッセージが表示されます。
後で戻り値が変更され、編集画面の読み込みプロセスが失敗する
コンテンツのタイプは保存されませんでした。
修正したら、もう一度選択し、Enterキーを押して正常にロードします。
![image](https://user-images.githubusercontent.com/503743/72157322-9a2d8c80-33f2-11ea-8e47-f80820fa3e34.png)
