### ISSUE TITLE
[サントリー]ミニアプリ部品：動画のVIEW　音声、プログレスバー、再生/停止などに対応

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#325]
miniapp.js
draw_comp_video.js

参考画像
![Horizontal video](https://user-images.githubusercontent.com/47316607/71507096-9a903880-28c6-11ea-8636-f830685d9fcd.png)
![Vertical video](https://user-images.githubusercontent.com/47316607/71507097-9a903880-28c6-11ea-9137-f1ec5cf35105.png)

**Comment by ToshikazuHorioka** [comment]
UIバグ

![IMG_0384](https://user-images.githubusercontent.com/47316607/71969411-f43f1e00-3249-11ea-8afd-77d193998f87.PNG)

**Comment by wheatup** [comment]
@soyoes
