### ISSUE TITLE
ミニアプリ作成中、順番がずれてしまった

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#348]
BOT ID : 1588
ミニアプリをインポートして作成した場合にこのような現象が起こるかもしれません。
確認お願いします。

元々のフォーム順
![Screenshot 2020-01-09 at 20 31 35](https://user-images.githubusercontent.com/47316607/72064617-9a108c80-331f-11ea-831b-1d35e980ebc4.png)

順番が正しくないミニアプリ
![Screenshot 2020-01-09 at 20 31 26](https://user-images.githubusercontent.com/47316607/72064696-c3c9b380-331f-11ea-9da7-2224d0759e88.png)

**Comment by liumu** [comment]
再現できないのに、インポートするときにインポート先の順番のみ処理するように修正
