### ISSUE TITLE
ブラウザを縮小するとAPP名がずれてしまう

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#349]
![Screenshot 2020-01-09 at 20 45 46](https://user-images.githubusercontent.com/47316607/72065317-4d2db580-3321-11ea-84c5-4fb1ab5a528e.png)

**Comment by ToshikazuHorioka** [comment]
一旦min-widthで指定する

**Comment by liumu** [comment]
長すぎる部分は… ように修正しました
