### ISSUE TITLE
混雑状況が正しく表示されない

### ISSUE THREAD

**Issue by evolany-kotori** [Evolany/anybot_issues#350]
bid=1329
app=clinick anybot

こちらのbotで正しく混雑状況が表示されません。
会話を作り直したり、APIを入力し直しても上手く表示されませんでした。

![iOS の画像のコピー](https://user-images.githubusercontent.com/52436160/72065307-499a2e80-3321-11ea-9d01-e3709f2413b7.png)

<img width="478" alt="スクリーンショット 2020-01-09 20 53 58" src="https://user-images.githubusercontent.com/52436160/72065941-b9f57f80-3322-11ea-9efc-f665d2859b3c.png">

apiでは正しくデータは取れています。
<img width="478" alt="スクリーンショット 2020-01-09 20 45 39" src="https://user-images.githubusercontent.com/52436160/72065195-0b047400-3321-11ea-95ca-e025c2ff4f73.png">

**Comment by liumu** [comment]
BotプランがStandard→Proへアップデート必要
