### ISSUE TITLE
Clinic : 予約、担当者を変えたら、データが消える

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#36]
バグ報告：予約管理画面
予約済みの予定の担当医を変更して保存すると情報が変更され、顧客名が「クライアント」となる。その上で画面更新すると予定自体が消えてしまいます。

**Comment by wheatup** [comment]
Fixed on commit:[6df4c268f8029a0c117c05b703bbcfbc7848df93](https://github.com/Evolany/anybot/commit/6df4c268f8029a0c117c05b703bbcfbc7848df93)
