### ISSUE TITLE
Webwidget版のbotが正常に表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#38]
大学LP用の問合せchatbot[anybot for college]を作成、
発行されたURL 動作確認の為　https://college.anybot.me/699にアクセス

初回の会話が正常に表示されず、
それ以降の会話に遷移できませんでした。

![IMG_3118](https://user-images.githubusercontent.com/49668745/66294204-68081c80-e923-11e9-8d10-a7dc160102f1.PNG)

**Comment by liumu** [comment]
初回登録時会話を選択されないため、導入段階に設定して会話できました。

![image](https://user-images.githubusercontent.com/5706609/66297445-45293880-e922-11e9-9943-0f9c8d8936ca.png)
