### ISSUE TITLE
大学 : 自動応答が動かない

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#40]
![191008001](https://user-images.githubusercontent.com/1071779/66383472-05cd1b80-e9f8-11e9-97c7-c712ec549d4c.JPG)
![191008002](https://user-images.githubusercontent.com/1071779/66383473-05cd1b80-e9f8-11e9-9395-3af0f597aa62.JPG)

自動応答＞未登録の質問＞遷移先の会話を指定しているのですが、LINE側で操作しても何も出てきません。管理画面の会話履歴では表示されているので反応しているようです。
至急ご対応いただきたいです。
※画像は「ロイヤル学園DEMO2」です。

**Comment by liumu** [comment]
「担当者呼び出し」ボタンのリアクションを指定していないので、LINE側でこのメッセージを作成できない。
当該ボタンのアクションを指定あるいはボタンを削除すれば解決できます。
