### ISSUE TITLE
[サントリー]ミニアプリの動画部品を秒数表示、お気に入り登録などのオンオフや配置場所のカスタマイズできるように

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#409]
左上の秒数表示のオン/オフ
お気に入りボタンのオン/オフ
家のアイコンはなんの機能か

配置場所を再生ボタンなどに変えた方が良いのでは？
動画の一部分が隠されてしまう

**Comment by wheatup** [comment]
Now the buttons only show when the video is paused.

**Comment by ToshikazuHorioka** [comment]
ここのホームアイコンとハートアイコンを押しても何も反応されません。
ユーザが混乱してしまうので、一旦ここも隠してくれますか？

![IMG_37C6B339DFCC-1](https://user-images.githubusercontent.com/47316607/73430913-81c1e980-4382-11ea-9178-dcb8cd9b2c50.jpeg)
