### ISSUE TITLE
ユーザーが送信したメッセージが個別トークに表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#45]
bot名：マナビズム
bot_id：932

ユーザー[6]が23:28に送信したメッセージ[おーい]のみ個別トーク画面で確認されなかった。
※その他送信されたメッセージは表示されている。

![72476827_443785436490008_8739073203890028544_n](https://user-images.githubusercontent.com/49668745/66538026-a852df00-eb5d-11e9-8af0-d59fd52a55e6.jpg)

<img width="667" alt="スクリーンショット 2019-10-10 12 57 03" src="https://user-images.githubusercontent.com/49668745/66537988-8194a880-eb5d-11e9-9d8b-c74a18c5dce2.png">

クライアントの懸念点
個別トークを利用する際にユーザーからのメッセージが表示されず、対応が遅れる

**Comment by liumu** [comment]
この時点でパッチ適用（実施時間が長かった）したので、メッセージデータを保存していない可能性が高い。
