### ISSUE TITLE
会話フローで取得したRESERVATIONSが予約画面に表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#454]
30.f (bot:id_1441)
**やりたい事**
ミニアプリ：体験クラススケジュール(空き時間)→デフォルト>12【無料体験予約内容確認】で取得した予約時間を予約管理に表示させたい。

**設定**
①ミニアプリ【体験クラススケジュール】で店舗(store_id_5394)空き時間を選択
②デフォルト>12【無料体験予約内容確認】でRESERVATIONSを指定

清水彩紀(ID:118)で5394の2020-02-15(土)に予約
**問題点**
選択した5394の予約内容が予約画面に反映されない。
<img width="1134" alt="スクリーンショット 2020-02-13 10 38 15" src="https://user-images.githubusercontent.com/49668745/74393270-f4d06300-4e4c-11ea-8670-dcddd1bcfa98.png">

**Comment by liumu** [comment]
拡張の予約Reservations画面上で、「予約キャンセル」がOFFに設定予約できる。
