### ISSUE TITLE
設定していない住所自動検索メッセージが表示される

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#52]
bot名：ラカラジャパン
bot_id：1164

企業情報>郵便番号[住所自動検索なし]
<img width="353" alt="スクリーンショット 2019-10-11 12 17 10" src="https://user-images.githubusercontent.com/49668745/66622141-a6525400-ec21-11e9-86d9-115d62280d66.png">

LINE上で下記メッセージが表示される
![IMG_3144](https://user-images.githubusercontent.com/49668745/66622154-aeaa8f00-ec21-11e9-84bb-f93750897fed.PNG)

**Comment by cntomxu** [comment]
ukey=zipcodeの時に住所自動保存のために作った標準機能。簡単な方法はukeyを変える
