### ISSUE TITLE
インフラ : 500番ERRの時に開発チームに自動通知できるように

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#56]

**Comment by liumu** [comment]
zabbixでアクセスログのhttp statusを監視しながら、500エラーが発見する場合、開発メンバーへ自動的に送信。送信内容は以下のように
![image](https://user-images.githubusercontent.com/5706609/67303360-f3d59780-f524-11e9-8d19-d5d0d3b0e697.png)
