### ISSUE TITLE
電話番号でマージされたユーザデータが別のユーザのものだった

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#59]
ボット名：【株式会社ファイブグループ】Hi-Five | 従業員向け
ボットID：1013

ID：10287 鈴木 開人さんがLINEでユーザー認証したが、槌野 貴士 さんのデータとマージしてしまった。

インポート時のCSVファイルがないため添付できませんが、以前のインポート時の重複ユーザが
おかしくなっている模様です。

**Comment by liumu** [comment]
ユーザマスタデータを再度インポートしているので、この件は一旦CLOSE。
