### ISSUE TITLE
miniapp：タイトル表示が2重で表示されてしまう

### ISSUE THREAD

**Issue by ShinyaHirata** [Evolany/anybot_issues#60]
bot名　anybot
bot_id 517

![image](https://user-images.githubusercontent.com/55083366/66700556-7ba0f200-ed2c-11e9-9672-2d7d079abfd7.png)

**Comment by soyoes** [comment]
@ShinyaHirata miniappの編集フォームで、説明とタイトル・プレースホルダーのそれぞれも同じコンテンツを入れていませんか？

**Comment by ShinyaHirata** [comment]
![image](https://user-images.githubusercontent.com/55083366/66746220-3a3f4c80-eebc-11e9-96e5-402c82c0dd47.png)

![image](https://user-images.githubusercontent.com/55083366/66746285-5642ee00-eebc-11e9-8d8e-08bb685c4169.png)

![image](https://user-images.githubusercontent.com/55083366/66746313-66f36400-eebc-11e9-9792-5a521c5e7fa3.png)

![image](https://user-images.githubusercontent.com/55083366/66746325-7377bc80-eebc-11e9-8311-84b667f9df6c.png)

※現在の設定はこちらの状態です。
