### ISSUE TITLE
至急：SMS認証コードが送信されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#62]
Bot名：【株式会社ファイブグループ】Hi-Five | 従業員向け
Bot_id：1013

1.[1910]ユーザ認証>③の[確定]ボタンにSMSを設定

デモ環境、本番でのその他のBotではSMSは送信されるが
Bot_id：1013でSMS送信が正常に作動しない。
![スクリーンショット 2019-10-11 23 54 51](https://user-images.githubusercontent.com/49668745/66795527-de1e0c00-ef3f-11e9-9ae3-e08af9c6dfac.png)

**Comment by liumu** [comment]
差出し人の制限があって、一旦クローズ
