### ISSUE TITLE
認証コード送信後に会話に遷移されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#64]
bot名：【株式会社ファイブグループ】Hi-Five | 従業員向け
bot_id：1013

1.[1910]ユーザ認証
認証コードを送信後に生年月日に遷移するよう設定しているが
LINEでは認証コードを送信しても会話に遷移せずフローが止まってしまう。

![Uploading スクリーンショット 2019-10-15 16.15.24.png…]()

**Comment by soyoes** [comment]
設定問題 codegen()は同じメッセージ内は2回以降使用する場合は {{user.verifycode}} を使ってください
