### ISSUE TITLE
ユーザ認証の再マージができない

### ISSUE THREAD

**Issue by ToshikazuHorioka** [Evolany/anybot_issues#65]
【株式会社ファイブグループ】Hi-Five | 従業員向け
 Bot ID:1013
ユーザID : 13730

CSVのユーザデータインポート後、電話番号を元にLINEユーザとの連携をしたい。
LINEでいただいた電話番号とインポートした電話番号が違った場合、以下のフローで再マージの作業を行なっています。

```
１）WEB情報に正しい電話番号を登録
２）LINEにて再度認証フロー（電話番号以下）を送付
３）認証が完了すると、WEB情報⇆LINE情報がマージされる
```

**Comment by cntomxu** [comment]
![image](https://user-images.githubusercontent.com/503743/66900925-464c1b00-f030-11e9-84b2-0c8c603faf03.png)
telは同じではない、ユーザーをマージすることはできません

**Comment by liumu** [comment]
csvファイルに載せた電話番号が間違っている場合、以下の手順によって再度マージを実施

1. LINEユーザ07011111111を設定
2. その後csvユーザに正しい電話番号を設定
3. その後会話フローを送信
4. 再度正しい電話番号を入力し、sdkユーザをマージする
