### ISSUE TITLE
イベント予約後に参加者がリストに表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#66]
anybot for college
bot名：関東学院大学
bot_id：516

会話グループ「1103_事前受付登録」の
39「確認_1」に「イベント予約」を設定会話ではいを選択しても、
イベントid　9746 | 11/3 臨時個別相談会（今年度受験生対象）の参加者リストに表示されない
※当該ボタンを押した際に「**リンク先のアクションは存在しないか、削除されています**」と
エラーメッセージが表示されます。

![スクリーンショット 2019-10-16 17 29 34](https://user-images.githubusercontent.com/49668745/66902122-13f3eb00-f03b-11e9-98dc-3254befef894.png)
<img width="744" alt="スクリーンショット 2019-10-16 17 07 31" src="https://user-images.githubusercontent.com/49668745/66902140-18200880-f03b-11e9-820c-e7a148225aa3.png">

**Comment by liumu** [comment]
ステップ①の中に、プログラム一覧を選択されてない原因
![image](https://user-images.githubusercontent.com/5706609/67008128-73292c80-f11b-11e9-93d9-3e352573726f.png)
