### ISSUE TITLE
イメージマップからテキストの会話に遷移されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#69]
Bot名：PROACTIVE
bot_id：1292
webhook接続済み
https://line.me/R/ti/p/@041hxobs

メニュー[よくある質問]→イメージマップ①→各カテゴリーのイメージマップ
各カテゴリからテキストへ遷移するように設定しているが会話が表示されない。
![IMG_3244](https://user-images.githubusercontent.com/49668745/66982639-8f17d880-f0f1-11e9-8631-dc4728bca6ba.PNG)

**Comment by liumu** [comment]
rect保存のロジック問題があって、問題がありすべて選択式ボタンを再保存し対応済み
