### ISSUE TITLE
ログインできない（パスワード再設定できない）

### ISSUE THREAD

**Issue by ChikaKageyama** [Evolany/anybot_issues#7]
selfonboarderの以下のメールアドレスが、ログインできないそうです。
パスワード再設定を行ったが、エラーで何もできなかったとのことです。

管理者からパスワードを変更して新しいパスワードを提供したのですが、
それでもログインできないそうです。

以下、メールアドレス
m-hosaka@hosaka-office.jp

再度ログインするにはどのようにすればよいでしょうか？

**Comment by soyoes** [comment]
誰かがプライベートemailで、pw忘れの機能を試してみて

**Comment by ChikaKageyama** [comment]
<img width="188" alt="キャプチャ" src="https://user-images.githubusercontent.com/48752463/66016087-2e44a980-e510-11e9-81d1-716e72c4735e.PNG">

**Comment by ChikaKageyama** [comment]
再設定メール来ませんでした。

**Comment by soyoes** [comment]
@ToshikazuHorioka どんな状況だっけ？

**Comment by ToshikazuHorioka** [comment]
@soyoes @ChikaKageyama 

こちら fixedです！
