### ISSUE TITLE
セグメントに応対するリッチメニューが一部ユーザーに表示されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#70]
Bot名：【株式会社ファイブグループ】Hi-Five | 従業員向け
bot_id：1013

対象ユーザー
ID[13752] 所属セグメント名[社員/Pecori]
ID[13761]  所属セグメント名[社員/FC]

上記2名が該当リッチメニューが表示されず、ユーザー認証前のリッチメニューのままになっている

**Comment by soyoes** [comment]
@ayakishimizu 今治った？
