### ISSUE TITLE
[大学]イベント参加者一覧 > キャンセルタグを付けたあとにもとに戻れない

### ISSUE THREAD

**Issue by soyoes** [Evolany/anybot_issues#73]

**Comment by soyoes** [comment]
@cntomxu 这个后来怎么样了？

**Comment by cntomxu** [comment]
@soyoes 
改完了，本番和dricom都更新了。
最开始做的时候特意不让 预约的按钮 点击，防止对预约人数上限有影响。
现在都上随便点了，每次点击也追加了count数的处理。
也因为可以随便点，这里不能使用简单的+1，所以我改成从db里的统计了。
然后rms_log也有同样的问题， 状态可以在管理画面随便改，也统一成使用db里的值直接算，要不然状态切换总数会加多了。
另外顺便把三个count算的不对的又重新算了一下，
追加了patch修正，总数应该没什么问题了。
