### ISSUE TITLE
User：作成したセグメントにユーザーが表示されなくなった

### ISSUE THREAD

**Issue by ShinyaHirata** [Evolany/anybot_issues#81]
bot=Gooday
bot_id="941"

![image](https://user-images.githubusercontent.com/55083366/67082917-12f6c100-f1d5-11e9-85d0-54a2e2a4e2cc.png)

![image](https://user-images.githubusercontent.com/55083366/67082953-2a35ae80-f1d5-11e9-8e88-3a037b2d2e1e.png)

**Comment by liumu** [comment]
https://github.com/Evolany/anybot/commit/28d13cfb6860fb026860bc02d06b1023d6b587ce
