### ISSUE TITLE
REFパラメータからセグメントタグが生成されない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#84]
bot名：ラカラジャパン
bot_id：1164

REFパラメーターを振った下記リンクからBotにアクセス

https://line.me/R/app/1653319129-lDwNo3Yk?type=app&b=1164&v=514&ref_store=CFプライム&sid=5146

![CF](https://user-images.githubusercontent.com/49668745/67171807-ae657d00-f3f3-11e9-805e-28c22737e583.png)

フォームは起動したが、これまで生成されていたREFタグが表示されなかった
![REF_segmentation](https://user-images.githubusercontent.com/49668745/67171902-28960180-f3f4-11e9-94b2-84e13cad3739.png)

**Comment by cntomxu** [comment]
REFは ‘ref’パラメーターに対応します
開発を追加し、「ref_xxx」を条件付き表示として設定しました。
図：
