### ISSUE TITLE
Request：個別トークの会話履歴表示

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#9]
**クライアントからの要望**
管理画面から個別トークを表示した際に
最終訪問時の会話履歴を表示してほしい

**現状**
新規登録時の一番古い会話履歴が一番最初に表示され、
最新の会話履歴を確認する為に毎回スクロールしなくてはならない。

<img width="653" alt="スクリーンショット 2019-10-03 10 36 01" src="https://user-images.githubusercontent.com/49668745/66093523-87254800-e5cb-11e9-96c1-118023f63d5d.png">

**Comment by ToshikazuHorioka** [comment]
対応済み
