### ISSUE TITLE
Basical attributesの登録日でセグメントが正常に取得できない

### ISSUE THREAD

**Issue by ayakishimizu** [Evolany/anybot_issues#90]
bot名：マナビズム
bot_id：932

LINEユーザー数：1586
basical attributesの登録日から1-0日間で
セグメントを作成した際に1574人が対象に表示されるが、
公開から数ヶ月経過している為この登録日でのセグメントが正常に機能しているのか
ご確認お願い致します。

![Basical attributes](https://user-images.githubusercontent.com/49668745/67189115-99efa780-f428-11e9-915b-799ed7b6a06e.png)

![スクリーンショット 2019-10-21 17 28 25](https://user-images.githubusercontent.com/49668745/67189131-a07e1f00-f428-11e9-8ad0-5700527c3683.png)

**Comment by liumu** [comment]
設定が逆に差し替えて、フィルタしたいユーザを表示されました。
![image](https://user-images.githubusercontent.com/5706609/67192421-26e53180-f426-11e9-9190-f01bc6d2e755.png)

**Comment by soyoes** [comment]
@liumu これはバグ？バグでなかったら、closeして
